version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}

  caddy:
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./front/build:/usr/share/nginx/html:ro
      - ./front/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    
  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
