const environment = {
  URL: import.meta.env.VITE_APP_URL,
  API_BASE_URL: import.meta.env.VITE_API_URL,
  STRIPE_PUBLISHABLE_KEY: import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY,
  STRIPE_PRICE_PRODUCT_SIXTY: import.meta.env.VITE_STRIPE_PRICE_PRODUCT_SIXTY,
  STRIPE_PRICE_PRODUCT_HUNDREDTWENTY: import.meta.env.VITE_STRIPE_PRICE_PRODUCT_HUNDREDTWENTY,
  STRIPE_PRICE_PRODUCT_TWOHUNDRED: import.meta.env.VITE_STRIPE_PRICE_PRODUCT_TWOHUNDRED,
}

export default environment
